Repository panoptes/POCS, pull requests merged in 2018-10, with the labels that each got.

#652 Remove cloud-sql information
  conf_files/pocs.yaml
  pocs/utils/db/__init__.py
  pocs/utils/db/postgres.py
  scripts/connect_clouddb_proxy.py
  scripts/startup/start_cloudsql_proxy.sh
  scripts/startup/start_panoptes_in_tmux.sh
Labels: Quick PR

#642 Camera image pathname cleanup
  pocs/camera/camera.py
  pocs/scheduler/observation.py
Labels: Quick PR

#654 Add manifest log for image uploads
  conf_files/pocs.yaml
  pocs/observatory.py
  pocs/tests/conftest.py
  pocs/tests/states/test_states.py
  pocs/tests/test_pocs.py
  pocs/utils/google/storage.py
  pocs/utils/images/__init__.py
  scripts/upload_files_to_bucket.sh
Labels: Quick PR

#659 Separate coarse autofocus from fine autofocus
  pocs/camera/camera.py
  pocs/focuser/focuser.py
  pocs/tests/test_camera.py
Labels: Enhancement, Testing, focuser

#635 Documentation Update (RTD & Sphinx) - WIP
  .codecov.yml
  .travis.yml
  docs/Makefile
  docs/README.md
  docs/_static/logo.png
  docs/_static/pan-head.png
  docs/_static/pan-title-black-transparent.png
  docs/_static/pocs-graph.png
  docs/conf.py
  docs/index.rst
  docs/panoptes-overview.rst
  docs/pocs-alternatives.rst
  docs/pocs-overview.rst
  docs/requirements.txt
  docs/source/modules.rst
  docs/source/pocs.camera.rst
  docs/source/pocs.dome.rst
  docs/source/pocs.focuser.rst
  docs/source/pocs.mount.rst
  docs/source/pocs.rst
  docs/source/pocs.scheduler.rst
  docs/source/pocs.sensors.rst
  docs/source/pocs.serial_handlers.rst
  docs/source/pocs.state.rst
  docs/source/pocs.state.states.default.rst
  docs/source/pocs.state.states.rst
  docs/source/pocs.utils.google.rst
  docs/source/pocs.utils.images.rst
  docs/source/pocs.utils.rst
  pocs/tests/__init__.py
  pocs/tests/bisque/__init__.py
  pocs/tests/data/__init__.py
  pocs/tests/utils/__init__.py
  pocs/tests/utils/google/__init__.py
  pocs/utils/__init__.py
  setup.cfg
Labels: Documentation

#663 More readthedocs fixes
  .readthedocs.yml
  docs/conf.py
  setup.cfg
Labels: Documentation, Quick PR

#669 Minor debug log output changes
  pocs/core.py
Labels: Merge on Approval, Quick PR

#670 Camera test tweaks from #547
  pocs/tests/test_camera.py
Labels: Camera, Quick PR, Testing

#673 Decouple serial utils
  pocs/tests/test_rs232.py
  pocs/utils/rs232.py
Labels: Merge on Approval, Quick PR

#672 Decouple custom exceptions from PanBase
  pocs/tests/utils/test_utils.py
  pocs/utils/error.py
Labels: Merge on Approval, Quick PR

#674 TheSkyX Updates
  pocs/dome/__init__.py
  pocs/utils/theskyx.py
  resources/bisque/dome/status.js
  resources/bisque/guider/autoguide.js
Labels: Merge on Approval, Quick PR

#680 Scrub paths from config load
  pocs/utils/config.py
Labels: Quick PR

#683 Refuse all google uploads for PAN00 and default to not uploading.
  pocs/observatory.py
  pocs/tests/conftest.py
  pocs/tests/test_observatory.py
  pocs/utils/images/__init__.py
Labels: Quick PR

#684 Updates to current_time
  bin/pocs_shell
  pocs/camera/camera.py
  pocs/tests/test_observatory.py
  pocs/tests/utils/test_utils.py
  pocs/utils/__init__.py
Labels: Quick PR

#688 Fixing a missing pointing image
  pocs/camera/canon_gphoto2.py
  pocs/state/states/default/pointing.py
Labels: Quick PR, bug

#690 Add DelaySigTerm to pocs/utils.
  pocs/tests/utils/test_utils.py
  pocs/utils/__init__.py
Labels: One of Many PRs, Quick PR

#694 Quick Camera fix
  pocs/camera/__init__.py
  pocs/camera/canon_gphoto2.py
  pocs/tests/test_camera.py
Labels: Quick PR, bug

#696 Fix autofocus tests
  pocs/tests/test_camera.py
Labels: Quick PR

#699 Use DelaySigTerm to cleanly stop ArduinoIO
  pocs/sensors/arduino_io.py
  pocs/tests/test_arduino_io.py
  pocs/utils/__init__.py
  pocs/utils/logger.py
  scripts/arduino_recorder.py
Labels: One of Many PRs, arduino

#701 Suppress the numpy DeprecationWarnings from astropy
  setup.cfg
Labels: Merge on Approval, Quick PR

#702 Implement PanMongoDb.permanently_erase_database for tests
  pocs/utils/database.py
Labels: Merge on Approval

#704 Fix messaging_ports to use sequential ports
  conftest.py
Labels: Merge on Approval, One of Many PRs, Quick PR, Testing

#706 Use non-production ports in the config test fixture
  pocs/tests/conftest.py
  pocs/tests/test_pocs.py
Labels: One of Many PRs, Testing

#714 Fix broken travis tests
  .travis.yml
  requirements.txt
Labels: Quick PR, bug
