Repository panoptes/POCS, pull requests merged in 2019-08, with the labels that each got.

#877 Remove unused test with deprecated features.
  conftest.py
  pocs/tests/utils/google/test_storage.py
  requirements.txt
Labels: Merge on Approval, Quick PR

#876 IERS Mirror
  pocs/utils/data.py
Labels: Merge on Approval, Quick PR

#875 db_name as fixture
  conftest.py
Labels: Merge on Approval, Quick PR, v0.7.0 Milestone

#888 Small mount updates
  pocs/mount/__init__.py
  pocs/mount/bisque.py
  pocs/mount/serial.py
Labels: Merge on Approval, Quick PR, v0.7.0 Milestone

#885 Fitlerwheel and focuser updates
  pocs/filterwheel/filterwheel.py
  pocs/filterwheel/simulator.py
  pocs/focuser/focuser.py
  pocs/utils/images/__init__.py
Labels: Merge on Approval, Quick PR, v0.7.0 Milestone

#874 Final step of adding create_mount_from_config
  pocs/observatory.py
  pocs/tests/test_observatory.py
  pocs/tests/test_pocs.py
Labels: GSoC, v0.7.0 Milestone

#887 Slew to home blocking
  bin/pocs_shell
  pocs/mount/bisque.py
  pocs/mount/mount.py
  pocs/mount/simulator.py
Labels: Merge on Approval, Quick PR, v0.7.0 Milestone
