Repository panoptes/POCS, pull requests merged in 2019-07, with the labels that each got.

#861 Ignore pytest warning errors
  setup.cfg
Labels: Merge on Approval, Quick PR

#864 add_scheduler/remove_scheduler changed to set_scheduler
  pocs/observatory.py
  pocs/tests/test_observatory.py
Labels: GSoC

#852 create_mount_from_config was created.
  pocs/mount/__init__.py
  pocs/tests/conftest.py
  pocs/tests/test_mount.py
  pocs/tests/test_observatory.py
  pocs/utils/error.py
Labels: GSoC

#746 Make google bucket transfer script more generic
  pocs/utils/google/storage.py
  scripts/transfer-files.sh
  scripts/upload_files.sh
Labels: Quick PR

#867 Minor fixes from recent PR merges.
  pocs/mount/__init__.py
  pocs/observatory.py
  pocs/tests/test_mount.py
  pocs/tests/test_observatory.py
Labels: GSoC, Quick PR

#857 Dynamic adding/removing dome.
  pocs/observatory.py
  pocs/tests/test_observatory.py
Labels: GSoC

#858 Dynamic adding/removing mount.
  pocs/observatory.py
  pocs/tests/test_observatory.py
Labels: GSoC

#871 Add TESS north fields
  resources/targets/tess_sectors_north.yaml
Labels: Quick PR

#870 Making `set_<hardware>` methods use a positional parameter
  pocs/observatory.py
  pocs/tests/test_observatory.py
Labels: GSoC
