Repository panoptes/POCS, pull requests merged in 2019-09, with the labels that each got.

#896 Remove separate PEAS config
  bin/peas_shell
  conf_files/peas.yaml
  conf_files/pocs.yaml
  peas/sensors.py
  peas/weather.py
  scripts/arduino_recorder.py
  scripts/plot_weather.py
Labels: Quick PR, v0.7.0 Milestone

#880 Read single sensor
  peas/sensors.py
  peas/tests/test_boards.py
  pocs/hardware.py
  pocs/sensors/arduino_io.py
  pocs/tests/test_filterwheel.py
  setup.cfg
Labels: v0.7.0 Milestone

#879 PEAS remote sensors
  peas/remote_sensors.py
  peas/tests/test_sensors.py
  pocs/tests/test_observatory.py
  requirements.txt
Labels: v0.7.0 Milestone

#898 Fix import of ctypes.util
  pocs/tests/utils/test_utils.py
  pocs/utils/library.py
Labels: Quick PR, bug
